version: '3.7'

services:

  jellyfin-exporter:
    image: rafaelvieiras/jellyfin-exporter:latest
    container_name: jellyfin-exporter
    ports:
      - "2112:2112"
    environment:
      - JELLYFIN_API_URL=http://192.168.100.16:8096
      - JELLYFIN_TOKEN=187f26bdb1cb495c876ab03c96550c5b
      - SERVER_PORT=2112
    volumes:
      - ./config.env:/app/config.env
    restart: unless-stopped
